### ISSUE TITLE
Add support for labels

### ISSUE THREAD

**Issue by ghost** [NerdWalletOSS/shepherd#590] opened 2022-06-06 21:39 UTC
It would be handy to be able to add labels (where supported) to PRs as part of this process.

**Comment by sdann** [comment] 2024-10-29 17:01
This looks to be a duplicate of issue https://github.com/NerdWalletOSS/shepherd/issues/54

**Comment by aorinevo** [comment] 2024-10-30 12:01
> This looks to be a duplicate of issue https://github.com/NerdWalletOSS/shepherd/issues/54

Yep, these seem to be the same.

**Comment by aorinevo** [comment] 2024-10-30 12:02
Closing in favor of #54

**Closed** 2024-10-30 12:02 UTC
Labels: enhancement, good first issue
